### ISSUE TITLE
Multiple tables

### ISSUE THREAD

**Issue by Thawab8** [johnonline35/pg-archiver#1]
Hello,

in the read me, you mention it's TABLE_NAME to extract. Is it possible to include multiple tables?

**Comment by johnonline35** [comment]
Changes made to support multiple tables:

1. Changed the environment variable from TABLE_NAME to TABLE_NAMES, which now accepts a comma-separated list of table names
2. Added TableName field to both IoTRecord and ParquetFile structs to track the source table.
3. Refactored the code to:
- Process multiple tables in sequence
- Combine records from all tables into a single Parquet file
- Delete archived records from each table separately
- Use a more descriptive S3 key prefix (multi_table_ instead of the table name)
